/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/common/Card.vue')['default']
    GameTable: typeof import('./src/components/black-jack/GameTable.vue')['default']
    Menu: typeof import('./src/components/common/Menu.vue')['default']
  }
}
